### PR TITLE
Convert Groovy script to Kotlin

### PR DESCRIPTION
**Pull request by dchaley**
I ran into several issues with the Groovy script. The one that stopped me was it loaded multiple classes via several class path loaders, likely due to the static members.

I think the original script is supposed to run in an embedded QuPath environment but we have the opposite task: to run outside QuPath after a DeepCell job finishes. So, I don't think we even need Groovy for anything other than consistency … which might be a big deal, we'll see.

Meanwhile I rewrote it in Kotlin as a "Groovy-like" language (in particular inferred types). I did a pretty literal rewrite for now, we should refactor at some point.

Kotlin compiles the normal way, it doesn't get interpreted or have a special runtime the way Groovy does.

### CODE REVIEW

**Comment by lynnlangit** [comment]
Not sure, but think your instinct (that the Groovy script requires an embedded QuPath env [and JVM] to run) is correct. Given that, is this approach (Kotlin, re-write?) actually viable?  Can you recommend a test for @bnovotny to perform on her env?

**Comment by dchaley** [comment]
If it's about running in the embedded environment, then there's not much we can do regardless of language (we want to kick off a process to initialize a QuPath project, once the DeepCell jobs finish).

The code does some work, especially with Intensity measurements turned on (in fact, it took so long I canceled it). So, I think it makes sense to have that in the cloud as part of "processing". 

We end up with some QuPath project files which I *think* could be downloaded straight away & used *except for* the path references. But if we can download it as a bundle and rewrite the paths, then it doesn't matter where we run it.

**Comment by bnovotny** [comment]
I **think** that if the files are in the same relative locations to the .qpproj file, QuPath will recognize the change of absolute path, and ask to rewrite them in the data. This happens a lot when we have a project on a network drive, and two users have the drive mapped differently to their PCs. So it might not be a problem once we download/copy the bundle... 

Hoping we can use QuPath on a VM in the cloud, but we will also probably still need to download it especially for use on PI's desktops.

The intensity measurements are the main output from QuPath for downstream analysis, so unfortunately we have to run that super long step 😫

**Comment by dchaley** [comment]
Thanks @bnovotny – that's really helpful. I took a video of what I think you mean here:

https://youtu.be/B_qpNkPzHzk

The only thing is I had to tell it where to look (the base directory containing OMETIFF, SEGMASKS, and the generated QUPATH data). But then it worked just fine.

I see online that QUPATH apparently likes it better if you put the images at the same location as `project.qpproj` file. Maybe, it auto-searches those locations.

The 1st script put the QuPath files in the same directory as the one containing OMETIFF. The 2nd script (which just had whole-cell masks) put it in the `QUPATH/` subdirectory. Are these conventions important?

I experimented with placing the project file at the same location like so:

Screenshot 2024-07-29 at 4 00 34 PM

QuPath still didn't automatically suggest the new paths however, it did mean "Search" started in the right directory.

**Comment by dchaley** [comment]
For reference: reading through this issue I found with @WeihaoGe1009 was really helpful
https://github.com/qupath/qupath/issues/266

which linked to this wiki page:
https://github.com/qupath/qupath/wiki/Projects

which eventually linked to a post about the "Search" button method:
https://petebankhead.github.io/qupath/2019/08/20/fourth-milestone.html#repair-projects-by-finding-missingmoved-images

We fiddled with relative paths for a while before concluding we were fighting QuPath's preference for absolute paths. We thought it was supposed to "just work" with relative paths– not that it could find the new absolute paths based on name matching.

**Pull request merged**
